INSERT INTO AccessHub VALUES(1, null);

INSERT INTO AccessPoint VALUES(1,1);
INSERT INTO AccessPoint VALUES(2,2);
INSERT INTO AccessPoint VALUES(3,3);
INSERT INTO AccessPoint VALUES(4,4);
INSERT INTO AccessPoint VALUES(5,5);
INSERT INTO AccessPoint VALUES(6,6);
INSERT INTO AccessPoint VALUES(7,7);
INSERT INTO AccessPoint VALUES(8,8);
INSERT INTO AccessPoint VALUES(9,9);
INSERT INTO AccessPoint VALUES(10,10);


